# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Lint, Test, and Build

on:
  release:
    types: [created]
  push:
    branches:
      - ci/github-action
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Authenticate to Google Cloud
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: mesh-432507
          install_components: "gcloud"
      - name: Prerun GCP auth
        run: |
          echo "$GCP_CREDENTIALS" > ./google-credentials.json && gcloud auth login --brief --cred-file=./google-credentials.json --update-adc
          gcloud auth configure-docker --quiet
      - name: Deploy Backend
        run: npm run deploy
